using System.Text.Json;
using TypeFerence.Core;
using Xunit;

namespace TypeFerence.Tests;

/// <summary>
/// Runs the shared cross-implementation conformance suite (repository
/// conformance/ directory). Digests in the fixture manifests are generated by
/// the Go implementation's runner; this class independently verifies that the
/// reference implementation produces the same bytes. A mismatch on any
/// fixture means the two implementations diverged.
/// </summary>
public sealed class ConformanceSuiteTests
{
    private static string FixturesRoot => Path.Combine(FindRoot(), "conformance", "fixtures");

    public static TheoryData<string> Fixtures()
    {
        var data = new TheoryData<string>();
        foreach (var dir in Directory.EnumerateDirectories(FixturesRoot).Order(StringComparer.Ordinal))
            data.Add(Path.GetFileName(dir));
        return data;
    }

    [Theory]
    [MemberData(nameof(Fixtures))]
    public void Fixture_MatchesExpectedOutcome(string name)
    {
        var dir = Path.Combine(FixturesRoot, name);
        using var manifest = JsonDocument.Parse(File.ReadAllText(Path.Combine(dir, "manifest.json")));
        var root = manifest.RootElement;
        var expect = root.GetProperty("expect").GetString();
        var emitArd = root.TryGetProperty("emitArd", out var domain) ? domain.GetString() : null;
        var trustSignatures = root.TryGetProperty("trustSignatures", out var signatures)
            ? Path.Combine(dir, signatures.GetString()!)
            : null;
        var allowUnsigned = root.TryGetProperty("allowUnsignedTrust", out var allow) && allow.GetBoolean();

        var source = Path.Combine(dir, "source");
        var output = Path.Combine(Path.GetTempPath(), "typeference-conformance-" + Guid.NewGuid().ToString("N"));
        try
        {
            var ard = emitArd is null ? null : new ArdPublicationOptions(emitArd, null, trustSignatures, allowUnsigned);
            var targets = new[] { CompilationTarget.Neutral, CompilationTarget.Codex, CompilationTarget.Copilot, CompilationTarget.Cursor };

            if (expect == "error")
            {
                Assert.Throws<TypeFerenceException>(() => new TypeFerenceCompiler().Build(source, output, targets, ard));
                return;
            }

            Assert.Equal("success", expect);
            new TypeFerenceCompiler().Build(source, output, targets, ard);
            var computed = Directory.EnumerateDirectories(output)
                .ToDictionary(
                    x => Path.GetFileName(x)!,
                    x => "sha256:" + TypeFerenceCompiler.HashDirectory(x),
                    StringComparer.Ordinal);

            var expected = root.GetProperty("digests").EnumerateObject()
                .ToDictionary(x => x.Name, x => x.Value.GetString()!, StringComparer.Ordinal);
            Assert.NotEmpty(expected);
            Assert.Equal(expected.Keys.Order(StringComparer.Ordinal), computed.Keys.Order(StringComparer.Ordinal));
            foreach (var pair in expected)
                Assert.True(pair.Value == computed[pair.Key],
                    $"{name}/{pair.Key}: digest mismatch\n got:  {computed[pair.Key]}\n want: {pair.Value}");
        }
        finally
        {
            if (Directory.Exists(output)) Directory.Delete(output, true);
        }
    }

    private static string FindRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "TypeFerence.slnx")))
            directory = directory.Parent;
        return directory?.FullName ?? throw new InvalidOperationException("Repository root not found");
    }
}
