// Package scaffold implements the deterministic setup wizard generator
// (ADR-0028): a versioned AnswerSet maps through Scaffold() to an in-memory
// SourceTree of an ordinary version 7 package. The package knows nothing
// about browsers, filesystems, tar archives, or standard output; the CLI and
// wasm bridge are its only intended consumers.
package scaffold

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// SchemaVersion is the AnswerSet schema this generator understands. Bumping
// it invalidates older answer sets unless the generator retains support.
const SchemaVersion = 1

var orgNameRe = regexp.MustCompile(`^[a-z0-9][a-z0-9-]*$`)
var semverRe = regexp.MustCompile(`^(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)$`)
var normIDRe = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)

// Norm is one behavioral statement the user writes as plain prose.
type Norm struct {
	ID   string `json:"id,omitempty"`
	Text string `json:"text"`
}

// TeamLevel is one level of the embedding chain (department, team, ...).
type TeamLevel struct {
	Name string `json:"name"`
}

// AgentSpec is the concrete agent at the end of the chain.
type AgentSpec struct {
	Name string `json:"name"`
}

// Targets selects which host artifacts to emit.
type Targets struct {
	Hosts []string `json:"hosts"`
}

// Organization is the identity block of an AnswerSet.
type Organization struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// AnswerSet is the wizard/init input document. Unknown fields are errors:
// even the wizard's own configuration is typed (ADR-0028).
type AnswerSet struct {
	SchemaVersion int          `json:"schemaVersion"`
	Organization  Organization `json:"organization"`
	Norms         []Norm       `json:"norms"`
	Levels        []TeamLevel  `json:"levels"`
	Agent         AgentSpec    `json:"agent"`
	Targets       Targets      `json:"targets"`
}

// ParseAnswerSet decodes and validates raw JSON into an AnswerSet. Every
// violation names its field; nothing is guessed.
func ParseAnswerSet(raw []byte) (*AnswerSet, error) {
	dec := json.NewDecoder(strings.NewReader(string(raw)))
	dec.DisallowUnknownFields()
	var as AnswerSet
	if err := dec.Decode(&as); err != nil {
		return nil, fmt.Errorf("invalid answer set: %v", err)
	}
	if err := as.validate(); err != nil {
		return nil, err
	}
	return &as, nil
}

func (as *AnswerSet) validate() error {
	if as.SchemaVersion != SchemaVersion {
		return fmt.Errorf("answer set schemaVersion must be %d, got %d", SchemaVersion, as.SchemaVersion)
	}
	if !orgNameRe.MatchString(as.Organization.Name) {
		return fmt.Errorf("organization.name must be a lowercase ascii identifier, got %q", as.Organization.Name)
	}
	if !semverRe.MatchString(as.Organization.Version) {
		return fmt.Errorf("organization.version must be an exact semantic version, got %q", as.Organization.Version)
	}
	if len(as.Norms) == 0 || len(as.Norms) > 5 {
		return fmt.Errorf("norms must contain between 1 and 5 statements")
	}
	seenNorm := map[string]bool{}
	for i, n := range as.Norms {
		id := n.ID
		if id == "" {
			id = slug(n.Text)
		}
		if id == "" || seenNorm[id] {
			return fmt.Errorf("norms[%d] has an empty or duplicate derived id", i)
		}
		if !normIDRe.MatchString(id) {
			return fmt.Errorf("norms[%d].id must use lowercase letters, digits, and single hyphens, got %q", i, id)
		}
		seenNorm[id] = true
		if strings.TrimSpace(n.Text) == "" {
			return fmt.Errorf("norms[%d].text must not be blank", i)
		}
	}
	if len(as.Levels) > 3 {
		return fmt.Errorf("at most 3 team levels are supported")
	}
	seenLevel := map[string]bool{"base": true}
	for i, l := range as.Levels {
		name := slug(l.Name)
		if name == "" || seenLevel[name] {
			return fmt.Errorf("levels[%d].name must be non-empty, unique, and not \"base\"", i)
		}
		seenLevel[name] = true
	}
	if slug(as.Agent.Name) == "" {
		return fmt.Errorf("agent.name is required and must contain letters or digits")
	}
	// Hosts do not change generated bytes. The retired host names stay
	// accepted so answer sets written before ADR-0029 remain valid.
	valid := map[string]bool{"agent-plugin": true, "neutral": true, "codex": true, "copilot": true, "cursor": true}
	if len(as.Targets.Hosts) == 0 {
		as.Targets.Hosts = []string{"neutral"}
	}
	for _, h := range as.Targets.Hosts {
		if !valid[h] {
			return fmt.Errorf("targets.hosts contains unknown host %q", h)
		}
	}
	sort.Strings(as.Targets.Hosts)
	return nil
}

func slug(text string) string {
	s := strings.ToLower(strings.TrimSpace(text))
	var b strings.Builder
	lastDash := false
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		case r == ' ', r == '-', r == '_':
			if !lastDash && b.Len() > 0 {
				b.WriteByte('-')
				lastDash = true
			}
		default:
			// skip other characters
		}
	}
	out := strings.Trim(b.String(), "-")
	if len(out) > 40 {
		out = out[:40]
		out = strings.Trim(out, "-")
	}
	return out
}

// GeneratorVersion identifies the generator in scaffold manifests. It changes
// with any commit that alters generated bytes for existing answer sets.
// 2.0.0 generates version 6 plugin sets (ADR-0030); 1.0.0 generated version 5
// suites and is preserved by the archived fixture 057.
const GeneratorVersion = "3.0.0"
